output "target_ip" {
  description = "Public IP of the VulnBoard host. This is everything the learner is given."
  value       = aws_instance.vulnboard.public_ip
}

output "webapp_url" {
  description = "VulnBoard URL (HTTP, port 8080)."
  value       = "http://${aws_instance.vulnboard.public_ip}:8080"
}

output "scenario_info" {
  description = "Deployment metadata."
  value = {
    scenario_name  = "code-judge-escape"
    scenario_id    = local.scenario_id
    region         = var.region
    whitelisted_ip = local.whitelist_cidr
  }
}

output "hint" {
  description = "Hint pointing at the intended entry vector."
  value       = "VulnBoard caches grading results in a cookie. Inspect the response headers after submitting code."
}

output "start_message" {
  description = "Challenge banner."
  value       = <<-EOF

    +------------------------------------------------------------------+
    |                                                                  |
    |                       CODE-JUDGE-ESCAPE                          |
    |                          Challenge Ready                         |
    |                                                                  |
    +------------------------------------------------------------------+

      Target IP : ${aws_instance.vulnboard.public_ip}
      VulnBoard : http://${aws_instance.vulnboard.public_ip}:8080
      Goal      : Read /app/data/flag.txt from inside the private
                  Fargate task (flag-vault container).

      Difficulty: Hard. The intended chain is five phases:
      pickle deserialization -> docker.sock abuse -> IMDSv2 ->
      ECS enumeration -> ecs:ExecuteCommand.

      All ingress is whitelisted to: ${local.whitelist_cidr}

    EOF
}

# --- Admin / debugging outputs (sensitive) -------------------------------

output "ecs_cluster_arn" {
  description = "ECS cluster ARN (admin only)."
  value       = aws_ecs_cluster.main.arn
  sensitive   = true
}

output "ecs_task_family" {
  description = "ECS task definition family name (admin only)."
  value       = aws_ecs_task_definition.flag_vault.family
  sensitive   = true
}

output "app_role_arn" {
  description = "EC2 instance role ARN (admin only)."
  value       = aws_iam_role.app.arn
  sensitive   = true
}

output "flag_location" {
  description = "Flag location inside the Fargate task (admin only)."
  value       = "flag-vault:/app/data/flag.txt"
  sensitive   = true
}

# --- target_info.txt asset materialization -------------------------------

resource "local_file" "target_info" {
  filename = "${path.module}/../assets/target_info.txt"
  content  = <<-EOF
    # GnawLab :: code-judge-escape
    # Auto-generated by terraform apply. Do not edit by hand.

    Target IP : ${aws_instance.vulnboard.public_ip}
    Web URL   : http://${aws_instance.vulnboard.public_ip}:8080
    Region    : ${var.region}

    Goal: retrieve /app/data/flag.txt from the private flag-vault container.
    EOF

  file_permission = "0644"
}
